from django.conf.urls.defaults import *

urlpatterns = patterns( 'events.views',
    url( r'^$', 'category', {'period': 'day'}, name = "event_main" ),
    url( r'^publica$', 'add', name = "event_add" ),
    url( r'^por-tipo/$', 'category', {'period': 'day'}, name="event_by_category" ),
    url( r'^por-tipo/dia$', 'category', {'period': 'day'}, name="event_by_category_day" ),
    url( r'^por-tipo/manana$', 'category', {'period': 'tomorrow'}, name="event_by_category_tomorrow" ),
    url( r'^por-tipo/dia/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])/(?P<day>[0-3]?\d)$', 'category', {'period': 'day'}, name="event_by_category_day_full" ),
    url( r'^por-tipo/manana/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])/(?P<day>[0-3]?\d)$', 'category', {'period': 'day', 'fake_tomorrow': True} ),
    url( r'^por-tipo/semana$', 'category' , {'period': 'week'}, name="event_by_category_week" ),
    url( r'^por-tipo/semana/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])/(?P<day>[0-3]?\d)$', 'category' , {'period': 'week'} ),
    url( r'^por-tipo/mes$', 'category' , {'period': 'month'}, name="event_by_category_month" ),
    url( r'^por-tipo/mes/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])$', 'category', {'period': 'month'} ),

    url( r'^por-zona$', 'area', {'period': 'day'}, name="event_by_area" ),
    url( r'^por-zona/dia$', 'area', {'period': 'day'}, name="event_by_area_day" ),
    url( r'^por-zona/manana$', 'area', {'period': 'tomorrow'}, name="event_by_area_tomorrow" ),
    url( r'^por-zona/dia/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])/(?P<day>[0-3]?\d)$', 'area', {'period': 'day'} ),
    url( r'^por-zona/manana/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])/(?P<day>[0-3]?\d)$', 'area', {'period': 'day', 'fake_tomorrow': True} ),
    url( r'^por-zona/semana$', 'area' , {'period': 'week'}, name="event_by_area_week" ),
    url( r'^por-zona/semana/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])/(?P<day>[0-3]?\d)$', 'area' , {'period': 'week'} ),
    url( r'^por-zona/mes$', 'area' , {'period': 'month'}, name="event_by_area_month" ),
    url( r'^por-zona/mes/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])$', 'area', {'period': 'month'} ),

    url( r'^por-musica$', 'music', {'period': 'day'}, name="event_by_music" ),
    url( r'^por-musica/dia$', 'music', {'period': 'day'}, name="event_by_music_day" ),
    url( r'^por-musica/manana$', 'music', {'period': 'tomorrow'}, name="event_by_music_tomorrow" ),
    url( r'^por-musica/dia/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])/(?P<day>[0-3]?\d)$', 'music', {'period': 'day'} ),
    url( r'^por-musica/manana/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])/(?P<day>[0-3]?\d)$', 'music', {'period': 'day', 'fake_tomorrow': True} ),
    url( r'^por-musica/semana$', 'music' , {'period': 'week'} , name="event_by_music_week"),
    url( r'^por-musica/semana/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])/(?P<day>[0-3]?\d)$', 'music' , {'period': 'week'} ),
    url( r'^por-musica/mes$', 'music' , {'period': 'month'} , name="event_by_music_month"),
    url( r'^por-musica/mes/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])$', 'music', {'period': 'month'} ),

    url( r'^por-sitios$', 'location' , {'period': 'day'}, name="event_by_location" ),
    url( r'^por-sitios/dia$', 'location', {'period': 'day'} , name="event_by_location_day"),
    url( r'^por-sitios/manana$', 'location', {'period': 'tomorrow'}, name="event_by_location_tomorrow" ),
    url( r'^por-sitios/dia/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])/(?P<day>[0-3]?\d)$', 'location', {'period': 'day'} ),
    url( r'^por-sitios/manana/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])/(?P<day>[0-3]?\d)$', 'location', {'period': 'day', 'fake_tomorrow': True} ),
    url( r'^por-sitios/semana$', 'location' , {'period': 'week'} , name="event_by_location_week"),
    url( r'^por-sitios/semana/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])/(?P<day>[0-3]?\d)$', 'location' , {'period': 'week'} ),
    url( r'^por-sitios/mes$', 'location' , {'period': 'month'}, name="event_by_location_month" ),
    url( r'^por-sitios/mes/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])$', 'location', {'period': 'month'} ),

    url( r'^calendario$', 'calendar_view' , {'period': 'month'}, name = "event_calendar" ),
    url( r'^calendario/(?P<year>\d{4})/(?P<month>0?[1-9]|1[012])$', 'calendar_view', {'period': 'month'}, name = "event_calendar_full" ),
    url( r'^(?P<slug>[-\w]+)/$', "detail", {'period': 'month'} , name = "event_details" ),
    url( r'^(?P<slug>[-\w]+)/por-tipo$', 'detail' , {'period': 'month'} ),
 )
